version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: book_catalogue_db
      DB_USER: root
      DB_PASSWORD: strongpassword

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: strongpassword
      MYSQL_DATABASE: book_catalogue_db
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

